spring:
  application:
    name: @project.artifactId@
  service:
    name: @project.artifactId@
  profiles:
    active: dev

scheduler:
  endangered:
    cron: "0 */10 * * * *"
  extinct:
    cron: "0 */10 * * * *"