spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:${MONGO_PORT}/${MONGO_DATABASE}
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}

server:
  port: 8099
